[package]
name = "image-proxy"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
salvo = { version = "0.37" }
tokio = { version = "1", features = ["macros"] }
reqwest = { version = "0.11", features = ["json"] }
image = "0.24.5"
http = "0.2.9"
